const initialState = {
  from: "",
  to: "",
  title: "",
  description: "",
  image: null,
  toInIssue: "",
  isLoading: false,
  isLoadingInShow: false,
  groupId: null,
  groupInEdit: null,
  groupName: "",
  groupMemberToInvite: "",
  groupAddress: "",
  groupPhone: "",
  groupIdInEdit: "",
  groupInShow: null,
  groupNameInEdit: "",
  groupAddressInEdit: "",
  groupPhoneInEdit: "",
  groupInIssuer: null,
  groupInSidebar: null,
  groupsInSidebar: [],
  userCert: {},
  certificateImage: "",
  userCerts: [],
  certificatesInIssuer: [],
  certificateInIssue: null,
  group: null,
  groups: [],
  profileInEdit: {},
  profileInShow: null,
  profileName: "",
  profileImage: "",
  imageCache: {},
  profileCache: {},
  usersToIssue: [],
  toList: [],
  myProfile: null,
  modalMessage: null,
  modalLink: null,
  modalLinkText: null,
};

export default initialState;
